# Generated by Django 3.2.9 on 2021-11-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('DeptID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_T',
            fields=[
                ('FacultyID', models.IntegerField(primary_key=True, serialize=False)),
                ('FacultyName', models.CharField(max_length=30)),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Room_T',
            fields=[
                ('RoomID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('RoomCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('SchoolTitle', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='SchoolTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.school_t'),
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('CourseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=30)),
                ('CreditHour', models.IntegerField()),
                ('CoOfferdCourse', models.CharField(max_length=7, null=True)),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('SectionID', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('SectionNum', models.IntegerField()),
                ('Semester', models.CharField(max_length=6)),
                ('Year', models.IntegerField()),
                ('SectionCapacity', models.IntegerField(null=True)),
                ('SectionEnrolled', models.IntegerField(null=True)),
                ('StartTime', models.TimeField(null=True)),
                ('EndTime', models.TimeField(null=True)),
                ('Day', models.CharField(max_length=2, null=True)),
                ('Blocked', models.CharField(max_length=3, null=True)),
                ('MaxSize', models.IntegerField(null=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasapp.course_t')),
                ('FacultyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.faculty_t')),
                ('RoomID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seasapp.room_t')),
            ],
            options={
                'unique_together': {('SectionNum', 'Semester', 'Year', 'CourseID')},
            },
        ),
    ]
