# Generated by Django 3.2.9 on 2021-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_t',
            name='DeptName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
