# Generated by Django 3.2.9 on 2021-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0002_alter_department_t_deptname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_t',
            name='DeptID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
