# Generated by Django 3.2.9 on 2021-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0004_auto_20211202_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_t',
            name='FacultyName',
            field=models.CharField(max_length=50),
        ),
    ]
