# Generated by Django 3.2.9 on 2021-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0007_alter_course_t_coursename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_t',
            unique_together={('CourseID', 'CoOfferdCourse')},
        ),
    ]
