# Generated by Django 3.2.9 on 2021-12-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0010_auto_20211203_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='coofferedcourse_t',
            name='Coofferredwith',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coofferredwith', to='seasapp.course_t'),
        ),
        migrations.AlterUniqueTogether(
            name='coofferedcourse_t',
            unique_together={('OfferedCourseID', 'Coofferredwith')},
        ),
        migrations.RemoveField(
            model_name='coofferedcourse_t',
            name='COFFERED_WITH',
        ),
    ]
