# Generated by Django 3.2.9 on 2021-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0011_auto_20211203_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='SectionID',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
