# Generated by Django 3.2.9 on 2021-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0012_alter_section_t_sectionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='Day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
