# Generated by Django 3.2.9 on 2021-12-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0013_alter_section_t_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_t',
            name='MaxSize',
        ),
    ]
