# Generated by Django 4.0 on 2021-12-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasapp', '0015_uploadfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfolder',
        ),
    ]
